# Cargo.toml
[package]
name = "habit-tracker"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
terminal_size = "0.4.3"
crossterm = "0.29"
clap = { version = "4.3", features = ["derive"] }
prettytable = "0.10"